<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('cities')->get()->count() == 0){
         DB::table('cities')->insert([
    [ 'id' => '2','name' => 'Port Blair','state_id' => '31','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '3','name' => 'Hyderabad','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '4','name' => 'Visakhapatnam','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '5','name' => 'Vijayawada','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '6','name' => 'Guntur','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '7','name' => 'Warangal','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '8','name' => 'Nellore','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '9','name' => 'Kurnool','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '10','name' => 'Kadapa','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '11','name' => 'Rajahmundry','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '12','name' => 'Kakinada','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '13','name' => 'Nizamabad','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '14','name' => 'Tirupati','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '15','name' => 'Karimnagar','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '16','name' => 'Anantapur','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '17','name' => 'Ramagundam','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '18','name' => 'Vizianagaram','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '19','name' => 'Secunderabad','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '20','name' => 'Ongole','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '21','name' => 'Eluru','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '22','name' => 'Nandyal','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '23','name' => 'Khammam','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '24','name' => 'Machilipatnam','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '25','name' => 'Adoni','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '26','name' => 'Tenali','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '27','name' => 'Proddatur','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '28','name' => 'Mahbubnagar','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '29','name' => 'Chittoor','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '30','name' => 'Hindupur','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '31','name' => 'Bhimavaram','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '32','name' => 'Madanapalle','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '33','name' => 'Nalgonda','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '34','name' => 'Guntakal','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '35','name' => 'Srikakulam','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '36','name' => 'Dharmavaram','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '37','name' => 'Gudivada','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '38','name' => 'Adilabad','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '39','name' => 'Narasaraopet','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '40','name' => 'Tadpatri','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '41','name' => 'Suryapet','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '42','name' => 'Tadepalligudem','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '43','name' => 'Miryalaguda','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '44','name' => 'Chilakaluripet','state_id' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '45','name' => 'Guwahati','state_id' => '2','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '46','name' => 'Silchar','state_id' => '2','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '47','name' => 'Dibrugarh','state_id' => '2','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '48','name' => 'Nagaon','state_id' => '2','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '49','name' => 'Patna','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '50','name' => 'Gaya','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '51','name' => 'Bhagalpur','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '52','name' => 'Muzaffarpur','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '53','name' => 'Biharsharif','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '54','name' => 'Darbhanga','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '55','name' => 'Purnia','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '56','name' => 'Arrah','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '57','name' => 'Begusarai','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '58','name' => 'Katihar','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '59','name' => 'Munger','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '60','name' => 'Chapra','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '61','name' => 'Dinapur Nizamat','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '62','name' => 'Saharsa','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '63','name' => 'Hajipur','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '64','name' => 'Sasaram','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '65','name' => 'Dehri','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '66','name' => 'Siwan','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '67','name' => 'Bettiah','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '68','name' => 'Motihari','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '69','name' => 'Bagaha','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '70','name' => 'Kishanganj','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '71','name' => 'Jamalpur','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '72','name' => 'Jehanabad','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '73','name' => 'Buxar','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '74','name' => 'Aurangabad','state_id' => '5','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '75','name' => 'Chandigarh','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '76','name' => 'Raipur','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '77','name' => 'Bhilai Nagar','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '78','name' => 'Korba','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '79','name' => 'Bilaspur','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '80','name' => 'Durg','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '81','name' => 'Rajnandgaon','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '82','name' => 'Raigarh','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '83','name' => 'Jagdalpur','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '84','name' => 'Ambikapur','state_id' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '85','name' => 'New Delhi','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '86','name' => 'Kirari Suleman Nagar','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '87','name' => 'NDMC','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '88','name' => 'Karawal Nagar','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '89','name' => 'Nangloi Jat','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '90','name' => 'Bhalswa Jahangir Pur','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '91','name' => 'Sultan Pur Majra','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '92','name' => 'Hastsal','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '93','name' => 'Deoli','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '94','name' => 'Dallo Pura','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '95','name' => 'Burari','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '96','name' => 'Mustafabad','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '97','name' => 'Gokal Pur','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '98','name' => 'Mandoli','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '99','name' => 'Delhi Cantonment','state_id' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '100','name' => 'Ahmedabad','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '101','name' => 'Surat','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '102','name' => 'Vadodara','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '103','name' => 'Rajkot','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '104','name' => 'Bhavnagar','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '105','name' => 'Jamnagar','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '106','name' => 'Junagadh','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '107','name' => 'Gandhidham','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '108','name' => 'Nadiad','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '109','name' => 'Gandhinagar','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '110','name' => 'Anand','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '111','name' => 'Morvi','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '112','name' => 'Mahesana','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '113','name' => 'Surendranagar Dudhrej','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '114','name' => 'Bharuch','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '115','name' => 'Vapi','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '116','name' => 'Navsari','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '117','name' => 'Veraval','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '118','name' => 'Porbandar','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '119','name' => 'Godhra','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '120','name' => 'Bhuj','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '121','name' => 'Botad','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '122','name' => 'Patan','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '123','name' => 'Palanpur','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '124','name' => 'Jetpur Navagadh','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '125','name' => 'Valsad','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '126','name' => 'Kalol','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '127','name' => 'Gondal','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '128','name' => 'Deesa','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '129','name' => 'Amreli','state_id' => '4','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '130','name' => 'Faridabad','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '131','name' => 'Gurgaon','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '132','name' => 'Rohtak','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '133','name' => 'Hisar','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '134','name' => 'Panipat','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '135','name' => 'Karnal','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '136','name' => 'Sonipat','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '137','name' => 'Yamunanagar','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '138','name' => 'Panchkula','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '139','name' => 'Bhiwani','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '140','name' => 'Ambala','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '141','name' => 'Sirsa','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '142','name' => 'Bahadurgarh','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '143','name' => 'Jind','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '144','name' => 'Thanesar','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '145','name' => 'Kaithal','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '146','name' => 'Rewari','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '147','name' => 'Palwal','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '148','name' => 'Jagadhri','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '149','name' => 'Ambala Sadar','state_id' => '6','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '150','name' => 'Shimla','state_id' => '7','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '151','name' => 'Srinagar','state_id' => '8','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '152','name' => 'Jammu','state_id' => '8','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '153','name' => 'Anantnag','state_id' => '8','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '154','name' => 'Dhanbad','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '155','name' => 'Ranchi','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '156','name' => 'Jamshedpur','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '157','name' => 'Bokaro Steel','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '158','name' => 'Mango','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '159','name' => 'Deoghar','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '160','name' => 'Adityapur','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '161','name' => 'Hazaribag','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '162','name' => 'Chas','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '163','name' => 'Giridih','state_id' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '164','name' => 'Bangalore','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '165','name' => 'Hubli and Dharwad','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '166','name' => 'Mysore','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '167','name' => 'Gulbarga','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '168','name' => 'Mangalore','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '169','name' => 'Belgaum','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '170','name' => 'Davanagere','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '171','name' => 'Bellary','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '172','name' => 'Bijapur','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '173','name' => 'Shimoga','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '174','name' => 'Tumkur','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '175','name' => 'Raichur','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '176','name' => 'Bidar','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '177','name' => 'Hospet','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '178','name' => 'Gadag and Betigeri','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '179','name' => 'Bhadravati','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '180','name' => 'Robertson Pet','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '181','name' => 'Chitradurga','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '182','name' => 'Kolar','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '183','name' => 'Mandya','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '184','name' => 'Hassan','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '185','name' => 'Udupi','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '186','name' => 'Chikmagalur','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '187','name' => 'Bagalkot','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '188','name' => 'Ranibennur','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '189','name' => 'Gangawati','state_id' => '9','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '190','name' => 'Thiruvananthapuram','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '191','name' => 'Kochi','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '192','name' => 'Kozhikode','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '193','name' => 'Kollam','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '194','name' => 'Thrissur','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '195','name' => 'Alappuzha','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '196','name' => 'Palakkad','state_id' => '10','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '197','name' => 'Indore','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '198','name' => 'Bhopal','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '199','name' => 'Gwalior','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '200','name' => 'Jabalpur','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '201','name' => 'Ujjain','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '202','name' => 'Dewas','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '203','name' => 'Satna','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '204','name' => 'Sagar','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '205','name' => 'Ratlam','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '206','name' => 'Rewa','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '207','name' => 'Murwara','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '208','name' => 'Singrauli','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '209','name' => 'Burhanpur','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '210','name' => 'Khandwa','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '211','name' => 'Morena','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '212','name' => 'Bhind','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '213','name' => 'Guna','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '214','name' => 'Shivpuri','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '215','name' => 'Vidisha','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '216','name' => 'Mandsaur','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '217','name' => 'Chhindwara','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '218','name' => 'Chhattarpur','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '219','name' => 'Neemuch','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '220','name' => 'Pithampur','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '221','name' => 'Damoh','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '222','name' => 'Hoshangabad','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '223','name' => 'Sehore','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '224','name' => 'Khargone','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '225','name' => 'Betul','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '226','name' => 'Seoni','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '227','name' => 'Datia','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '228','name' => 'Nagda','state_id' => '11','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '229','name' => 'Mumbai','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '230','name' => 'Pune','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '231','name' => 'Nagpur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '232','name' => 'Thane','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '233','name' => 'Pimpri and Chinchwad','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '234','name' => 'Nashik','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '235','name' => 'Kalyan and Dombivali','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '236','name' => 'Vasai Virar','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '237','name' => 'Aurangabad','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '238','name' => 'Navi Mumbai','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '239','name' => 'Solapur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '240','name' => 'Mira and Bhayander','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '241','name' => 'Bhiwandi','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '242','name' => 'Amravati','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '243','name' => 'Nanded Waghala','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '244','name' => 'Kolapur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '245','name' => 'Ulhasnagar','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '246','name' => 'Sangli Miraj Kupwad','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '247','name' => 'Malegaon','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '248','name' => 'Jalgaon','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '249','name' => 'Akola','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '250','name' => 'Latur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '251','name' => 'Dhule','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '252','name' => 'Ahmadnagar','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '253','name' => 'Chandrapur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '254','name' => 'Parbhani','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '255','name' => 'Ichalkaranji','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '256','name' => 'Jalna','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '257','name' => 'Ambernath','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '258','name' => 'Navi Mumbai Panvel Raigad','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '259','name' => 'Bhusawal','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '260','name' => 'Panvel','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '261','name' => 'Badalapur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '262','name' => 'Bid','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '263','name' => 'Gondiya','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '264','name' => 'Satara','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '265','name' => 'Barshi','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '266','name' => 'Yavatmal','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '267','name' => 'Achalpur','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '268','name' => 'Osmanabad','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '269','name' => 'Nandurbar','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '270','name' => 'Wardha','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '271','name' => 'Udgir','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '272','name' => 'Hinganghat','state_id' => '12','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '273','name' => 'Imphal','state_id' => '13','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '274','name' => 'Shillong','state_id' => '14','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '275','name' => 'Aizawl','state_id' => '15','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '276','name' => 'Dimapur','state_id' => '16','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '277','name' => 'Bhubaneswar','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '278','name' => 'Cuttack','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '279','name' => 'Brahmapur Town','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '280','name' => 'Raurkela','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '281','name' => 'Raurkela Industrial Township','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '282','name' => 'Puri Town','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '283','name' => 'Sambalpur','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '284','name' => 'Baleshwar','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '285','name' => 'Baripada','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '286','name' => 'Bhadrak','state_id' => '17','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '287','name' => 'Ozhukarai','state_id' => '26','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '288','name' => 'Puducherry','state_id' => '26','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '289','name' => 'Ludhiana','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '290','name' => 'Amritsar','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '291','name' => 'Jalandhar','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '292','name' => 'Patiala','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '293','name' => 'Bathinda','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '294','name' => 'Hoshiarpur','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '295','name' => 'Batala','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '296','name' => 'Moga','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '297','name' => 'Pathankot','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '298','name' => 'Mohali','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '299','name' => 'Abohar','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '300','name' => 'Malerkotla','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '301','name' => 'Khanna','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '302','name' => 'Muktsar','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '303','name' => 'Barnala','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '304','name' => 'Firozpur','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '305','name' => 'Kapurthala','state_id' => '18','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '306','name' => 'Jaipur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '307','name' => 'Jodhpur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '308','name' => 'Kota','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '309','name' => 'Bikaner','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '310','name' => 'Ajmer','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '311','name' => 'Udaipur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '312','name' => 'Bhilwara','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '313','name' => 'Alwar','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '314','name' => 'Bharatpur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '315','name' => 'Sikar','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '316','name' => 'Pali','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '317','name' => 'Ganganagar','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '318','name' => 'Tonk','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '319','name' => 'Kishangarh','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '320','name' => 'Hanumangarh','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '321','name' => 'Beawar','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '322','name' => 'Dhaulpur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '323','name' => 'Sawai Madhopur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '324','name' => 'Churu','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '325','name' => 'Gangapur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '326','name' => 'Jhunjhunun','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '327','name' => 'Baran','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '328','name' => 'Chittaurgarh','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '329','name' => 'Hindaun','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '330','name' => 'Bhiwadi','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '331','name' => 'Bundi','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '332','name' => 'Nagaur','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '333','name' => 'Sujangarh','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '334','name' => 'Banswara','state_id' => '19','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '335','name' => 'Gangtok','state_id' => '20','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '336','name' => 'Chennai','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '337','name' => 'Coimbatore','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '338','name' => 'Madurai','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '339','name' => 'Tiruchirappalli','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '340','name' => 'Salem','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '341','name' => 'Tirunelveli','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '342','name' => 'Ambattur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '343','name' => 'Tiruppur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '344','name' => 'Avadi','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '345','name' => 'Tiruvottiyur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '346','name' => 'Thoothukkudi','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '347','name' => 'Nagercoil','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '348','name' => 'Thanjavur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '349','name' => 'Pallavaram','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '350','name' => 'Dindigul','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '351','name' => 'Vellore','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '352','name' => 'Tambaram','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '353','name' => 'Cuddalore','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '354','name' => 'Alandur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '355','name' => 'Kancheepuram','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '356','name' => 'Erode','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '357','name' => 'Tiruvannamalai','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '358','name' => 'Kumbakonam','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '359','name' => 'Rajapalayam','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '360','name' => 'Kurichi','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '361','name' => 'Madavaram','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '362','name' => 'Pudukkottai','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '363','name' => 'Hosur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '364','name' => 'Ambur','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '365','name' => 'Karaikkudi','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '366','name' => 'Neyveli','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '367','name' => 'Nagapattinam','state_id' => '21','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '368','name' => 'Agartala','state_id' => '22','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '369','name' => 'Lucknow','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '370','name' => 'Kanpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '371','name' => 'Ghaziabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '372','name' => 'Agra','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '373','name' => 'Meerut','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '374','name' => 'Varanasi','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '375','name' => 'Allahabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '376','name' => 'Bareilly','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '377','name' => 'Moradabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '378','name' => 'Aligarh','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '379','name' => 'Saharanpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '380','name' => 'Gorakhpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '381','name' => 'Noida','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '382','name' => 'Firozabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '383','name' => 'Loni','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '384','name' => 'Jhansi','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '385','name' => 'Muzaffarnagar','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '386','name' => 'Mathura','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '387','name' => 'Shahjahanpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '388','name' => 'Rampur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '389','name' => 'Maunath Bhanjan','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '390','name' => 'Farrukhabad and Fatehgarh','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '391','name' => 'Hapur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '392','name' => 'Etawah','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '393','name' => 'Mirzapur and Vindhyachal','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '394','name' => 'Bulandshahr','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '395','name' => 'Sambhal','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '396','name' => 'Amroha','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '397','name' => 'Fatehpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '398','name' => 'Rae Bareli','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '399','name' => 'Khora','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '400','name' => 'Orai','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '401','name' => 'Bahraich','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '402','name' => 'Jaunpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '403','name' => 'Unnao','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '404','name' => 'Sitapur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '405','name' => 'Faizabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '406','name' => 'Budaun','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '407','name' => 'Banda','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '408','name' => 'Lakhimpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '409','name' => 'Hathras','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '410','name' => 'Lalitpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '411','name' => 'Modinagar','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '412','name' => 'Deoria','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '413','name' => 'Pilibhit','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '414','name' => 'Hardoi','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '415','name' => 'Mainpuri','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '416','name' => 'Etah','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '417','name' => 'Basti','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '418','name' => 'Chandausi','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '419','name' => 'Gonda','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '420','name' => 'Akbarpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '421','name' => 'Khurja','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '422','name' => 'Azamgarh','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '423','name' => 'Ghazipur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '424','name' => 'Mughalsarai','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '425','name' => 'Kanpur Cantonment','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '426','name' => 'Sultanpur','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '427','name' => 'Shikohabad','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '428','name' => 'Shamli','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '429','name' => 'Ballia','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '430','name' => 'Baraut','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '431','name' => 'Greater Noida','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '432','name' => 'Kasganj','state_id' => '23','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '433','name' => 'Dehradun','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '434','name' => 'Hardwar','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '435','name' => 'Haldwani and Kathgodam','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '436','name' => 'Rudrapur','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '437','name' => 'Kashipur','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '438','name' => 'Roorkee','state_id' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '439','name' => 'Kolkata','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '440','name' => 'Haora','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '441','name' => 'Durgapur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '442','name' => 'Asansol','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '443','name' => 'Siliguri','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '444','name' => 'Maheshtala','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '445','name' => 'Rajpur Sonarpur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '446','name' => 'South Dum Dum','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '447','name' => 'Rajarhat Gopalpur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '448','name' => 'Bhatpara','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '449','name' => 'Panihati','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '450','name' => 'Kamarhati','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '451','name' => 'Barddhaman','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '452','name' => 'Kulti','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '453','name' => 'Bally','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '454','name' => 'Barasat','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '455','name' => 'North Dum Dum','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '456','name' => 'Baranagar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '457','name' => 'Uluberia','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '458','name' => 'Naihati','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '459','name' => 'Bidhan Nagar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '460','name' => 'Kharagpur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '461','name' => 'English Bazar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '462','name' => 'Haldia','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '463','name' => 'Madhyamgram','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '464','name' => 'Baharampur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '465','name' => 'Raiganj','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '466','name' => 'Serampore','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '467','name' => 'Hugli and Chinsurah','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '468','name' => 'Medinipur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '469','name' => 'Chandannagar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '470','name' => 'Uttarpara Kotrung','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '471','name' => 'Krishnanagar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '472','name' => 'Barrackpur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '473','name' => 'Santipur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '474','name' => 'Balurghat','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '475','name' => 'Habra','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '476','name' => 'Jamuria','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '477','name' => 'Bankura','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '478','name' => 'North Barrackpur','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '479','name' => 'Raniganj','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '480','name' => 'Nabadwip','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '481','name' => 'Basirhat','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '482','name' => 'Halisahar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '483','name' => 'Rishra','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '484','name' => 'Ashokenagar Kalyangarh','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '485','name' => 'Baidyabati','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '486','name' => 'Puruliya','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '487','name' => 'Kanchrapara','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '488','name' => 'Dabgram','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '489','name' => 'Darjiling','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '490','name' => 'Titagarh','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '491','name' => 'Dum Dum','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '492','name' => 'Bally Town','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '493','name' => 'Champdani','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '494','name' => 'Bongaon','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '495','name' => 'Khardaha','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '496','name' => 'Jalpaiguri','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '497','name' => 'Bansberia','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '498','name' => 'Bhadreswar','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '499','name' => 'Kalyani','state_id' => '24','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1554','name' => 'Hyderabad','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1555','name' => 'Warangal','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1556','name' => 'Nizamabad','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1557','name' => 'Khammam','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1558','name' => 'Ramagundam','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1559','name' => 'Karimnagar','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1560','name' => 'Mahbubnagar','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1561','name' => 'Nalgonda','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1562','name' => 'Adilabad','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1563','name' => 'Miryalaguda','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
	[ 'id' => '1564','name' => 'Suryapet','state_id' => '89','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ]
        ]);
     }
    }
}
