<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       if(DB::table('countries')->get()->count() == 0){
         DB::table('countries')->insert([
        [ 'id' => '1','name' => 'Afghanistan','code' => 'AFG','phone_code' => '93','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '2','name' => 'Aland Islands','code' => 'ALA','phone_code' => '358','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '3','name' => 'Albania','code' => 'ALB','phone_code' => '355','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '4','name' => 'Algeria','code' => 'DZA','phone_code' => '213','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '5','name' => 'American Samoa','code' => 'ASM','phone_code' => '1683','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '6','name' => 'Andorra','code' => 'AND','phone_code' => '376','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '7','name' => 'Angola','code' => 'AGO','phone_code' => '244','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '8','name' => 'Anguilla','code' => 'AIA','phone_code' => '1263','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '9','name' => 'Antarctica','code' => 'ATA','phone_code' => '672','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '10','name' => 'Antigua and Barbuda','code' => 'ATG','phone_code' => '1267','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '11','name' => 'Argentina','code' => 'ARG','phone_code' => '54','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '12','name' => 'Armenia','code' => 'ARM','phone_code' => '374','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '13','name' => 'Aruba','code' => 'ABW','phone_code' => '297','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '14','name' => 'Australia','code' => 'AUS','phone_code' => '61','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '15','name' => 'Austria','code' => 'AUT','phone_code' => '43','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '16','name' => 'Azerbaijan','code' => 'AZE','phone_code' => '994','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '17','name' => 'Bahamas','code' => 'BHS','phone_code' => '1241','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '18','name' => 'Bahrain','code' => 'BHR','phone_code' => '973','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '19','name' => 'Bangladesh','code' => 'BGD','phone_code' => '880','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '20','name' => 'Barbados','code' => 'BRB','phone_code' => '1245','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '21','name' => 'Belarus','code' => 'BLR','phone_code' => '375','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '22','name' => 'Belgium','code' => 'BEL','phone_code' => '32','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '23','name' => 'Belize','code' => 'BLZ','phone_code' => '501','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '24','name' => 'Benin','code' => 'BEN','phone_code' => '229','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '25','name' => 'Bermuda','code' => 'BMU','phone_code' => '1440','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '26','name' => 'Bhutan','code' => 'BTN','phone_code' => '975','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '27','name' => 'Bolivia','code' => 'BOL','phone_code' => '591','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '28','name' => 'Bonaire','code' => '','phone_code' => 'BES','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '29','name' => 'Bosnia and Herzegovina','code' => 'BIH','phone_code' => '387','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '30','name' => 'Botswana','code' => 'BWA','phone_code' => '267','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '31','name' => 'Bouvet Island (Bouvetoya)','code' => 'BVT','phone_code' => '47','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '32','name' => 'Brazil','code' => 'BRA','phone_code' => '55','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '33','name' => 'British Indian Ocean Territory (Chagos Archipelago)','code' => 'IOT','phone_code' => '246','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '34','name' => 'British Virgin Islands','code' => 'VGB','phone_code' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '35','name' => 'Brunei Darussalam','code' => 'BRN','phone_code' => '673','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '36','name' => 'Bulgaria','code' => 'BGR','phone_code' => '359','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '37','name' => 'Burkina Faso','code' => 'BFA','phone_code' => '226','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '38','name' => 'Burundi','code' => 'BDI','phone_code' => '257','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '39','name' => 'Cambodia','code' => 'KHM','phone_code' => '855','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '40','name' => 'Cameroon','code' => 'CMR','phone_code' => '237','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '41','name' => 'Canada','code' => 'CAN','phone_code' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '42','name' => 'Cape Verde','code' => 'CPV','phone_code' => '238','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '43','name' => 'Cayman Islands','code' => 'CYM','phone_code' => '1344','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '44','name' => 'Central African Republic','code' => 'CAF','phone_code' => '236','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '45','name' => 'Chad','code' => 'TCD','phone_code' => '235','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '46','name' => 'Chile','code' => 'CHL','phone_code' => '56','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '47','name' => 'China','code' => 'CHN','phone_code' => '86','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '48','name' => 'Christmas Island','code' => 'CXR','phone_code' => '61','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '49','name' => 'Cocos (Keeling) Islands','code' => 'CCK','phone_code' => '61','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '50','name' => 'Colombia','code' => 'COL','phone_code' => '57','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '51','name' => 'Comoros','code' => 'COM','phone_code' => '269','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '52','name' => 'Congo','code' => 'COG','phone_code' => '242','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '53','name' => 'Cook Islands','code' => 'COK','phone_code' => '682','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '54','name' => 'Costa Rica','code' => 'CRI','phone_code' => '506','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '55','name' => 'Cote dIvoire','code' => 'CIV','phone_code' => '385','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '56','name' => 'Croatia','code' => 'HRV','phone_code' => '53','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '57','name' => 'Cuba','code' => 'CUB','phone_code' => '599','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '58','name' => 'Curacao','code' => 'CUW','phone_code' => '357','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '59','name' => 'Cyprus','code' => 'CYP','phone_code' => '420','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '60','name' => 'Czech Republic','code' => 'CZE','phone_code' => '225','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '61','name' => 'Denmark','code' => 'DNK','phone_code' => '45','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '62','name' => 'Djibouti','code' => 'DJI','phone_code' => '253','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '63','name' => 'Dominica','code' => 'DMA','phone_code' => '1766','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '64','name' => 'Dominican Republic','code' => 'DOM','phone_code' => '1808','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '65','name' => 'Ecuador','code' => 'ECU','phone_code' => '593','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '66','name' => 'Egypt','code' => 'EGY','phone_code' => '20','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '67','name' => 'El Salvador','code' => 'SLV','phone_code' => '503','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '68','name' => 'Equatorial Guinea','code' => 'GNQ','phone_code' => '240','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '69','name' => 'Eritrea','code' => 'ERI','phone_code' => '291','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '70','name' => 'Estonia','code' => 'EST','phone_code' => '372','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '71','name' => 'Ethiopia','code' => 'ETH','phone_code' => '251','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '72','name' => 'Falkland Islands (Malvinas)','code' => 'FLK','phone_code' => '500','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '73','name' => 'Faroe Islands','code' => 'FRO','phone_code' => '298','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '74','name' => 'Fiji','code' => 'FJI','phone_code' => '679','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '75','name' => 'Finland','code' => 'FIN','phone_code' => '358','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '76','name' => 'France','code' => 'FRA','phone_code' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '77','name' => 'French Guiana','code' => 'GUF','phone_code' => '594','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '78','name' => 'French Polynesia','code' => 'PYF','phone_code' => '689','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '79','name' => 'French Southern Territories','code' => 'ATF','phone_code' => '262','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '80','name' => 'Gabon','code' => 'GAB','phone_code' => '241','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '81','name' => 'Gambia','code' => 'GMB','phone_code' => '220','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '82','name' => 'Georgia','code' => 'GEO','phone_code' => '995','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '83','name' => 'Germany','code' => 'DEU','phone_code' => '49','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '84','name' => 'Ghana','code' => 'GHA','phone_code' => '233','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '85','name' => 'Gibraltar','code' => 'GIB','phone_code' => '350','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '86','name' => 'Greece','code' => 'GRC','phone_code' => '30','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '87','name' => 'Greenland','code' => 'GRL','phone_code' => '299','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '88','name' => 'Grenada','code' => 'GRD','phone_code' => '1472','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '89','name' => 'Guadeloupe','code' => 'GLP','phone_code' => '590','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '90','name' => 'Guam','code' => 'GUM','phone_code' => '1670','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '91','name' => 'Guatemala','code' => 'GTM','phone_code' => '502','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '92','name' => 'Guernsey','code' => 'GGY','phone_code' => '44','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '93','name' => 'Guinea','code' => 'GIN','phone_code' => '224','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '94','name' => 'Guinea-Bissau','code' => 'GNB','phone_code' => '245','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '95','name' => 'Guyana','code' => 'GUY','phone_code' => '592','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '96','name' => 'Haiti','code' => 'HTI','phone_code' => '509','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '97','name' => 'Heard Island and McDonald Islands','code' => 'HMD','phone_code' => '672','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '98','name' => 'Holy See (Vatican City State)','code' => 'VAT','phone_code' => '33','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '99','name' => 'Honduras','code' => 'HND','phone_code' => '504','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '100','name' => 'Hong Kong','code' => 'HKG','phone_code' => '852','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '101','name' => 'Hungary','code' => 'HUN','phone_code' => '36','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '102','name' => 'Iceland','code' => 'ISL','phone_code' => '354','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '103','name' => 'India','code' => 'IND','phone_code' => '91','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '104','name' => 'Indonesia','code' => 'IDN','phone_code' => '62','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '105','name' => 'Iran','code' => 'IRN','phone_code' => '98','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '106','name' => 'Iraq','code' => 'IRQ','phone_code' => '964','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '107','name' => 'Ireland','code' => 'IRL','phone_code' => '353','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '108','name' => 'Isle of Man','code' => 'IMN','phone_code' => '44','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '109','name' => 'Israel','code' => 'ISR','phone_code' => '972','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '110','name' => 'Italy','code' => 'ITA','phone_code' => '39','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '111','name' => 'Jamaica','code' => 'JAM','phone_code' => '1875','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '112','name' => 'Japan','code' => 'JPN','phone_code' => '81','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '113','name' => 'Jersey','code' => 'JEY','phone_code' => '44','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '114','name' => 'Jordan','code' => 'JOR','phone_code' => '962','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '115','name' => 'Kazakhstan','code' => 'KAZ','phone_code' => '7','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '116','name' => 'Kenya','code' => 'KEN','phone_code' => '254','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '117','name' => 'Kiribati','code' => 'KIR','phone_code' => '686','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '118','name' => 'North Korea','code' => 'PRK','phone_code' => '850','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '119','name' => 'South Korea','code' => 'KOR','phone_code' => '82','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '120','name' => 'Kuwait','code' => 'KWT','phone_code' => '965','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '121','name' => 'Kyrgyz Republic','code' => 'KGZ','phone_code' => '996','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '122','name' => 'Lao Peoples Democratic Republic','code' => 'LAO','phone_code' => '856','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '123','name' => 'Latvia','code' => 'LVA','phone_code' => '371','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '124','name' => 'Lebanon','code' => 'LBN','phone_code' => '961','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '125','name' => 'Lesotho','code' => 'LSO','phone_code' => '266','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '126','name' => 'Liberia','code' => 'LBR','phone_code' => '231','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '127','name' => 'Libya','code' => 'LBY','phone_code' => '218','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '128','name' => 'Liechtenstein','code' => 'LIE','phone_code' => '423','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '129','name' => 'Lithuania','code' => 'LTU','phone_code' => '370','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '130','name' => 'Luxembourg','code' => 'LUX','phone_code' => '352','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '131','name' => 'Macao','code' => 'MAC','phone_code' => '853','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '132','name' => 'Macedonia','code' => 'MKD','phone_code' => '389','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '133','name' => 'Madagascar','code' => 'MDG','phone_code' => '261','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '134','name' => 'Malawi','code' => 'MWI','phone_code' => '265','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '135','name' => 'Malaysia','code' => 'MYS','phone_code' => '60','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '136','name' => 'Maldives','code' => 'MDV','phone_code' => '960','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '137','name' => 'Mali','code' => 'MLI','phone_code' => '223','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '138','name' => 'Malta','code' => 'MLT','phone_code' => '356','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '139','name' => 'Marshall Islands','code' => 'MHL','phone_code' => '692','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '140','name' => 'Martinique','code' => 'MTQ','phone_code' => '596','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '141','name' => 'Mauritania','code' => 'MRT','phone_code' => '222','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '142','name' => 'Mauritius','code' => 'MUS','phone_code' => '230','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '143','name' => 'Mayotte','code' => 'MYT','phone_code' => '262','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '144','name' => 'Mexico','code' => 'MEX','phone_code' => '52','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '145','name' => 'Micronesia','code' => 'FSM','phone_code' => '691','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '146','name' => 'Moldova','code' => 'MDA','phone_code' => '373','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '147','name' => 'Monaco','code' => 'MCO','phone_code' => '377','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '148','name' => 'Mongolia','code' => 'MNG','phone_code' => '976','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '149','name' => 'Montenegro','code' => 'MNE','phone_code' => '382','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '150','name' => 'Montserrat','code' => 'MSR','phone_code' => '1663','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '151','name' => 'Morocco','code' => 'MAR','phone_code' => '212','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '152','name' => 'Mozambique','code' => 'MOZ','phone_code' => '258','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '153','name' => 'Myanmar','code' => 'MMR','phone_code' => '95','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '154','name' => 'Namibia','code' => 'NAM','phone_code' => '264','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '155','name' => 'Nauru','code' => 'NRU','phone_code' => '674','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '156','name' => 'Nepal','code' => 'NPL','phone_code' => '977','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '157','name' => 'Netherlands','code' => 'NLD','phone_code' => '31','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '158','name' => 'New Caledonia','code' => 'NCL','phone_code' => '687','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '159','name' => 'New Zealand','code' => 'NZL','phone_code' => '64','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '160','name' => 'Nicaragua','code' => 'NIC','phone_code' => '505','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '161','name' => 'Niger','code' => 'NER','phone_code' => '227','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '162','name' => 'Nigeria','code' => 'NGA','phone_code' => '234','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '163','name' => 'Niue','code' => 'NIU','phone_code' => '683','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '164','name' => 'Norfolk Island','code' => 'NFK','phone_code' => '672','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '165','name' => 'Northern Mariana Islands','code' => 'MNP','phone_code' => '-669','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '166','name' => 'Norway','code' => 'NOR','phone_code' => '47','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '167','name' => 'Oman','code' => 'OMN','phone_code' => '968','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '168','name' => 'Pakistan','code' => 'PAK','phone_code' => '92','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '169','name' => 'Palau','code' => 'PLW','phone_code' => '680','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '170','name' => 'Palestine','code' => 'PSE','phone_code' => '970','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '171','name' => 'Panama','code' => 'PAN','phone_code' => '507','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '172','name' => 'Papua New Guinea','code' => 'PNG','phone_code' => '675','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '173','name' => 'Paraguay','code' => 'PRY','phone_code' => '595','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '174','name' => 'Peru','code' => 'PER','phone_code' => '51','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '175','name' => 'Philippines','code' => 'PHL','phone_code' => '63','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '176','name' => 'Pitcairn Islands','code' => 'PCN','phone_code' => '870','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '177','name' => 'Poland','code' => 'POL','phone_code' => '48','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '178','name' => 'Portugal','code' => 'PRT','phone_code' => '351','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '179','name' => 'Puerto Rico','code' => 'PRI','phone_code' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '180','name' => 'Qatar','code' => 'QAT','phone_code' => '974','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '181','name' => 'Reunion','code' => 'REU','phone_code' => '262','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '182','name' => 'Romania','code' => 'ROU','phone_code' => '40','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '183','name' => 'Russian Federation','code' => 'RUS','phone_code' => '7','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '184','name' => 'Rwanda','code' => 'RWA','phone_code' => '250','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '185','name' => 'Saint Barthelemy','code' => 'BLM','phone_code' => '590','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '186','name' => 'Saint Helena','code' => '','phone_code' => 'SHN','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '187','name' => 'Saint Kitts and Nevis','code' => 'KNA','phone_code' => '-868','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '188','name' => 'Saint Lucia','code' => 'LCA','phone_code' => '-757','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '189','name' => 'Saint Martin','code' => 'MAF','phone_code' => '590','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '190','name' => 'Saint Pierre and Miquelon','code' => 'SPM','phone_code' => '508','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '191','name' => 'Saint Vincent and the Grenadines','code' => 'VCT','phone_code' => '-783','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '192','name' => 'Samoa','code' => 'WSM','phone_code' => '685','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '193','name' => 'San Marino','code' => 'SMR','phone_code' => '378','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '194','name' => 'Sao Tome and Principe','code' => 'STP','phone_code' => '239','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '195','name' => 'Saudi Arabia','code' => 'SAU','phone_code' => '966','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '196','name' => 'Senegal','code' => 'SEN','phone_code' => '221','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '197','name' => 'Serbia','code' => 'SRB','phone_code' => '381','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '198','name' => 'Seychelles','code' => 'SYC','phone_code' => '248','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '199','name' => 'Sierra Leone','code' => 'SLE','phone_code' => '232','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '200','name' => 'Singapore','code' => 'SGP','phone_code' => '65','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '201','name' => 'Sint Maarten (Dutch part)','code' => 'SXM','phone_code' => '-720','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '202','name' => 'Slovakia (Slovak Republic)','code' => 'SVK','phone_code' => '421','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '203','name' => 'Slovenia','code' => 'SVN','phone_code' => '386','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '204','name' => 'Solomon Islands','code' => 'SLB','phone_code' => '677','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '205','name' => 'Somalia','code' => 'SOM','phone_code' => '252','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '206','name' => 'South Africa','code' => 'ZAF','phone_code' => '27','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '207','name' => 'South Georgia and the South Sandwich Islands','code' => 'SGS','phone_code' => '500','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '208','name' => 'South Sudan','code' => 'SSD','phone_code' => '211','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '209','name' => 'Spain','code' => 'ESP','phone_code' => '34','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '210','name' => 'Sri Lanka','code' => 'LKA','phone_code' => '94','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '211','name' => 'Sudan','code' => 'SDN','phone_code' => '249','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '212','name' => 'Suriname','code' => 'SUR','phone_code' => '597','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '213','name' => 'Svalbard & Jan Mayen Islands','code' => 'SJM','phone_code' => '47','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '214','name' => 'Swaziland','code' => 'SWZ','phone_code' => '268','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '215','name' => 'Sweden','code' => 'SWE','phone_code' => '46','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '216','name' => 'Switzerland','code' => 'CHE','phone_code' => '41','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '217','name' => 'Syrian Arab Republic','code' => 'SYR','phone_code' => '963','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '218','name' => 'Taiwan','code' => 'TWN','phone_code' => '886','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '219','name' => 'Tajikistan','code' => 'TJK','phone_code' => '992','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '220','name' => 'Tanzania','code' => 'TZA','phone_code' => '255','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '221','name' => 'Thailand','code' => 'THA','phone_code' => '66','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '222','name' => 'Timor-Leste','code' => 'TLS','phone_code' => '670','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '223','name' => 'Togo','code' => 'TGO','phone_code' => '228','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '224','name' => 'Tokelau','code' => 'TKL','phone_code' => '690','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '225','name' => 'Tonga','code' => 'TON','phone_code' => '676','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '226','name' => 'Trinidad and Tobago','code' => 'TTO','phone_code' => '1867','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '227','name' => 'Tunisia','code' => 'TUN','phone_code' => '216','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '228','name' => 'Turkey','code' => 'TUR','phone_code' => '90','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '229','name' => 'Turkmenistan','code' => 'TKM','phone_code' => '993','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '230','name' => 'Turks and Caicos Islands','code' => 'TCA','phone_code' => '1648','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '231','name' => 'Tuvalu','code' => 'TUV','phone_code' => '688','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '232','name' => 'Uganda','code' => 'UGA','phone_code' => '256','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '233','name' => 'Ukraine','code' => 'UKR','phone_code' => '380','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '234','name' => 'United Arab Emirates','code' => 'ARE','phone_code' => '971','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '235','name' => 'United Kingdom','code' => 'GBR','phone_code' => '44','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '236','name' => 'United States Minor Outlying Islands','code' => 'USA','phone_code' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '237','name' => 'United States of America','code' => 'UMI','phone_code' => '246','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '238','name' => 'United States Minor Outlying Islands','code' => 'URY','phone_code' => '598','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '239','name' => 'Uruguay','code' => 'UZB','phone_code' => '998','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '240','name' => 'United States Virgin Islands','code' => 'VIR','phone_code' => '1','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '241','name' => 'Uzbekistan','code' => 'VUT','phone_code' => '678','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '242','name' => 'Vanuatu','code' => 'VEN','phone_code' => '58','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '243','name' => 'Venezuela','code' => '/im','phone_code' => 'VNM','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '244','name' => 'Vietnam','code' => 'VGB','phone_code' => '1283','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '245','name' => 'Virgin Islands','code' => '','phone_code' => 'VIR','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '246','name' => 'Virgin Islands','code' => '','phone_code' => 'WLF','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '247','name' => 'Wallis and Futuna','code' => 'ESH','phone_code' => '212','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '248','name' => 'Western Sahara','code' => 'YEM','phone_code' => '967','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '249','name' => 'Yemen','code' => 'ZMB','phone_code' => '260','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '250','name' => 'Zambia','code' => 'ZWE','phone_code' => '263','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '251','name' => 'Zimbabwe','code' => 'ALA','phone_code' => '358','entity_status' => 'Active','created_by' => 'System','updated_by' => 'System' ],
		[ 'id' => '253','name' => 'Test Lalit','code' => 'UUU','phone_code' => '91','entity_status' => 'Deleted','created_by' => 'System','updated_by' => 'System' ]
        ]);
     }
    }
}
