<?php

return [

    /*
    |--------------------------------------------------------------------------
    | CONSTANT Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, We use constant for assets path, assets admin path.
    | error validation message
    */

	'error' => [
		'Required' => "This field can't be empty",
		'LoginEmail' => 'These credentials do not match our records',
		'ValidEmail' => 'Please enter valid Email',
		'LoginPass' => 'Please enter a valid password.',
		'LoginPassMinLength' => 'Password must be between 6 and 30 characters',
		'ModuleNameMinLength' => 'Module name must greater than 2 characters',
		'RoleNameMinLength' => 'Role name must greater than 2 characters',
		'ModuleNotFound' => 'Module does not exists',
		'RoleNotFound' => 'Role does not exists',
		'CountryNameMinLength' => 'Country name must greater than 2 characters',
		'CountryNotFound' => 'Country does not exists',
		'StateNameMinLength' => 'State name must greater than 2 characters',
		'StateNotFound' => 'State does not exists',
		'CityNameMinLength' => 'City name must greater than 2 characters',
		'CityNotFound' => 'City does not exists',
	],
	'success' => [
		'ModuleSaveSuccess' => 'Module saved successfully.',
		'RoleSaveSuccess' => 'Role saved successfully.',
		'CountrySaveSuccess' => 'Country saved successfully.',
		'StateSaveSuccess' => 'State saved successfully.',
		'StateSaveSuccess' => 'City saved successfully.',
	],
	'subject' => [
		
	],
	'dateFormate'=>'d-m-Y h:iA',
];



/* 	'error' => [
		'RoleIdError' => 'Role Id not found.',
		'EmailNotActivated' => 'Please activate your email id.',
		'UserInactiveOrDeleted' => 'User is %status%.',
		'RoleInactive' => '%role% is currently Inactive. Please contact admin for further information',
		'AccountInactive' => 'Your account is not activated yet.',
		'SendMail' => 'There is some error in sending mail. Please try again.',
		'ActivationUrlWrong' => 'Please check the url. it is not correct.',
		'TokenNotGenerated' => 'Token not generated. Please try again.',
		'SomeErrorTryAgain' => 'There is some error. please try again',
		'PassSameOldPass' => 'Old password and new password should not be same',
		'OldPassNotCorrect' => 'Old password is not matched in our records',
		'NothingToUpdate' => 'There is nothing to update',
		'PermissionError' => 'Permission Id not found.',
		'UserIdError' => 'User Id not found.',
		'TagIdError' => 'Tag Id not found.',
		'CategoryIdError' => 'Category Id not found.',
		'CountryIdError' => 'Country Id not found.',
		'StateIdError' => 'State Id not found.',
		'CityIdError' => 'City Id not found.',
		'CurrencyIdError' => 'City Id not found.',
		'ErrorLogIdError' => 'Error Log Id not found.',
		'LocalityIdError' => 'Locality Log Id not found.',
		'TaxIdError' => 'Tax Id not found.',
		'MarginIdError' => 'Margin Id not found.',
		'TaxNumaric' => 'Tax rate should be numeric.',
		'MarginNumaric' => 'Margin rate should be numeric.',
		'PhoneAlreadyVerified' => 'Phone Number is already varified.',
		'OTPMisMatch' => 'OTP is not correct. Please try again!',
		'PhoneNotActivated' => 'Phone Number is not verified yet. Please verify it.',
		'NumberMisMatch' => 'Phone Number is not matched. Please send OTP again.',
		'TaxNameValRequired' => 'Tax name and value is required.',
		'MarginNameValRequired' => 'Margin name and value is required.',
		'TaxUnique' => 'Tax name should be unique.',
		'TaxNValNumeric' => 'Tax value should be numeric.',
		'MarginUnique' => 'Margin name should be unique.',
		'MarginNValNumeric' => 'Margin value should be numeric.',
		'SmsNotAllowed' => 'SMS not allowed.',
		'EmailSendingError' => 'This email is not registered with amazon service.',
	],
	'success' => [
		'RoleAdded' => 'Role created successfully.',
		'RoleUpdated' => 'Role updated successfully.',
		'RoleDeleted' => 'Role deleted successfully.',
		'Login' => 'Login successfully.',
		'UserRegisterSuccess' => 'User registration successfully.',
		'SellerRegisterSuccess' => 'Seller registration successfully.',
		'PassResetMailSend' => 'Password reset link send successfully. Please check your Email',
		'PassUpdated' => 'Password updated successfully.',
		'PermissionUpdated' => 'Permission updated successfully.',
		'UserCreated' => 'User created successfully.',
		'UserUpdated' => 'User updated successfully.',
		'ProfileUpdated' => 'Profile updated successfully.',
		'ComapnyProfileUpdated' => 'Company profile updated successfully.',
		'AccountActivatedSuccess' => 'Your account activated successfully.',
		'TagAdded' => 'Tag created successfully.',
		'TagUpdated' => 'Tag updated successfully.',
		'TagDeleted' => 'Tag deleted successfully.',
		'CategoryAdded' => 'Category created successfully.',
		'CategoryUpdated' => 'Category updated successfully.',
		'CategoryDeleted' => 'Category deleted successfully.',
		'CountryAdded' => 'Country created successfully.',
		'CountryUpdated' => 'Country updated successfully.',
		'CountryDeleted' => 'Country deleted successfully.',
		'StateAdded' => 'State created successfully.',
		'StateUpdated' => 'State updated successfully.',
		'StateDeleted' => 'State deleted successfully.',
		'CityAdded' => 'City created successfully.',
		'CityUpdated' => 'City updated successfully.',
		'CityDeleted' => 'City deleted successfully.',
		'CurrencyAdded' => 'Currency created successfully.',
		'CurrencyUpdated' => 'Currency updated successfully.',
		'CurrencyDeleted' => 'Currency deleted successfully.',
		'ProductUpdated' => 'Product update successfully.',
		'ProductAdded' => 'Product save successfully.',
		'ErrorLogUpdated' => 'Error Log updated successfully.',
		'ErrorLogDeleted' => 'Error Log deleted successfully.',
		'LocalityAdded' => 'Locality created successfully.',
		'LocalityUpdated' => 'Locality updated successfully.',
		'LocalityDeleted' => 'Locality deleted successfully.',
		'TaxDeleted' => 'Tax deleted successfully.',
		'MarginDeleted' => 'Margin deleted successfully.',
		'TaxUpdated' => 'Tax updated successfully.',
		'TaxAdded' => 'Tax created successfully.',
		'MarginAdded' => 'Margin created successfully.',
		'MarginUpdated' => 'Margin updated successfully.',
		'OTPSend' => 'OTP send successfully.',
		'OTPMatchedEmailVerify' => 'OTP confirmation successfully. For Email verification, Please check your email id.',
		'OTPMatchPleaseContinue' => 'OTP verified successfully. Please continue.',
		'OTPSendOnUpdate' => 'We sent you OTP on new Number. Please verify your number first.',
		'EmailVerifiedMobileVerification' => 'Email confirmation successfully. Please verify your phone number.',
		'OTPMatchedAccountActivated' => 'OTP confirm and Account successfully  activated.',
		'UserAccountCreatedPhoneVerify' => 'User account has been created successfully. Please verify your phone number.',
		'BankDetailUpdated' => 'Bank detail updated successfully.',
		'OTPMessage' => '%OTP% is your OTP to verify your phone on gangplank',
	],
	'subject' => [
		'OTPMessage' => '%OTP% is your OTP to verify your phone on gangplank',
		'ResetYourPassword' => 'Reset your password',
		'PhoneUpdated' => 'Phone updated on gangplank',
		'ActivateYourEmail' => 'Welcome to gangplank !',
		'RegisterByAdmin' => 'Welcome to gangplank !',
		'UpdatePass' => 'Password Updated',
		'UpdatePassByAdmin' => 'Password reset successfully',
		'ContentUpdateByCurator' => 'We improved your video - %VideoCaption%',
		'PriceSuggestByCurator' => 'We suggested a new price for - %VideoCaption%',
		'RegisterByCompany' => 'Welcome to gangplank !',
		'ProductUploadedMail' => 'Your video has been processed',
		'ProductPurchase' => 'Thank you for your purchase on gangplank',
		'ProductSell' => 'Congratulations ! A new sale for your video %videoCaption% just happened.',
		'ProductSellNotification' => 'Congratulations ! A new sale for your video %videoCaption% just happened.',
		'CuratorPriceSuggested' =>  'We suggested a new price for  - %videoCaption%',
		'CuratorContentUpdate' =>  'We improved your video - %videoCaption%',
		'BuyerAccountActivatedMail' =>  'Account Activated !',
		'SellerAccountActivatedMail' =>  'Account Activated !',
		'ProductUploadedEmail' =>  'Your video has been processed',
		'ProductUploadNote' =>  'Your video %videoCaption% is uploaded successfully and now available on gangplank. Here is the preview link to your video %videoLink% .',
		'DownloadVideoMail' =>  '%videoCaption% downloaded recently',
		'DownloadVideoNote' =>  '%downloadUserName% downloaded the video %videoCaption%. Remaining downloads  %videoDownloaded%/3',
 */
